name: frontend

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
      - '.github/**'

defaults:
  run:
    working-directory: frontend

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  deploy: # job間で実行環境は共有されない
    if: github.event_name == 'push' # git pushされた時だけdeployを実行
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::956589521004:role/udemy-github-actions-frontend-deployment-role
          aws-region: ap-northeast-1

      - run: aws s3 sync . s3://j-sample-upload --exact-timestamps --region ap-northeast-1


